# frozen_string_literal: true

lane :test do
  version = check_good_version
  major_version = /(\d+)\..*/.match(version)[1]

  UI.user_error!("Using an outdated version of the GD.sdk, please upgrade") if major_version.to_i < 2
  UI.message("Using #{version} of the GD.sdk")
end
